export enum ObjectTypesEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',

  USER = 'USER',
  PUBLIC_USER = 'USER',
  USER_LITE = 'USER_LITE',

  GENERIC_OBJECT = 'GENERIC_OBJECT',
  PUBLIC_GENERIC_OBJECT = 'PUBLIC_GENERIC_OBJECT',
  GENERIC_OBJECT_LITE = 'GENERIC_OBJECT_LITE',

  NONE = 'NONE',
}
