export enum ObjectTypesEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',

  USER = 'USER',
  PUBLIC_USER = 'USER',
  USER_LITE = 'USER_LITE',

  CHAT_ROOM = 'CHAT_ROOM',
  PARTICIPANT = 'PARTICIPANT',
  MESSAGE = 'MESSAGE',

  GENERIC_OBJECT_BASIC = 'GENERIC_OBJECT_BASIC',
  GENERIC_OBJECT = 'GENERIC_OBJECT',
  PUBLIC_GENERIC_OBJECT = 'PUBLIC_GENERIC_OBJECT',
  GENERIC_OBJECT_LITE = 'GENERIC_OBJECT_LITE',

  NONE = 'NONE',
}
