export * from './DeepPartial';
export * from './IGenericObject';
export * from './IGenericObjectBasic';
export * from './IGenericObjectLite';
export * from './IIdentifiableUuid';
export * from './IPublicGenericObject';
export * from './IWritableGenericObject';
export * from './IWritablePublicGenericObject';
export * from './Nullable';
